# chef client c6
#
# VERSION 0.0.1

FROM centos:centos6
MAINTAINER Fletcher Davis reddot357@hotmail.com

RUN rpm -Uvh https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-11.16.4-1.el6.x86_64.rpm
ADD chef /root/.chef
ADD chef-repo /root/chef-repo
